version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/" 
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
  - package-ecosystem: "npm"
    directory: "/admin"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
  - package-ecosystem: "npm"
    directory: "/waiter"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
  - package-ecosystem: "npm"
    directory: "/fake-printer"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
  - package-ecosystem: "gomod"
    directory: "/printer-api"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
