services:
  api:
    build: api/
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: development
      GMBH_DB_USER: gmbh
      GMBH_DB_PASSWORD: gmbh
      GMBH_DB_NAME: gmbh
      GMBH_DB_HOST: mysql
      GMBH_DB_PORT: "3306"
      GMBH_DB_DIALECT: mysql
      PORT: "8080"
  order:
    build: order/
    ports:
      - "4200:4200"
      - "7020:7020" # dev server
    volumes:
      - ./order/app:/app/app
      # - shared_app:/app/dist
  mysql:
    image: mysql:8.0.44-bookworm
    environment:
      MYSQL_DATABASE: gmbh
      MYSQL_USER: gmbh
      MYSQL_PASSWORD: gmbh
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs/server:/etc/nginx/certs/server:ro
      - ./nginx/certs/ca:/etc/nginx/certs/ca:ro
      - ./nginx/cert-install:/app/cert-install:ro
      # - shared_app:/app/order:ro
    depends_on:
      - api
      - order
    extra_hosts:
      - "gmbh.local:127.0.0.1"
volumes:
  mysql_data:
  shared_app:
