version: "3.9"

services:
  api:
    build: api/
    command: ["npm", "test"]

  mysql:
    volumes:
      - mysql_test_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d:ro

volumes:
  mysql_test_data:
